# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGNlMzYyYjM0MmNkOTBkZTgyNmRmZjE4OGFmM2RkODhjOTA3MzM5OTkwMDJjODAxNWJmNjM5MTMxOGJjYTUzZGM2OWE3MzJiZDZmODdmZjQ5NGNjNmJjYWE1MmY0NzkwOTA4YzQ3YzA1ZjJkNjA1ZDllOGFmNWJjMWRhNjNmZDk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
